version: '3.8'
services:
  cassandra1:
    image: cassandra:latest
    container_name: cas1-lib
    networks:
      - cassandraNetwork
    ports:
      - "127.0.0.1:9042:9042"
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=cassandra1
      - CASSANDRA_LISTEN_ADDRESS=cassandra1
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3

  cassandra2:
    image: cassandra:latest
    container_name: cas2-lib
    networks:
      - cassandraNetwork
    ports:
      - "127.0.0.2:9042:9043"
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=cassandra2
      - CASSANDRA_LISTEN_ADDRESS=cassandra2
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3

  cassandra3:
    image: cassandra:latest
    container_name: cas3-lib
    networks:
      - cassandraNetwork
    ports:
      - "127.0.0.3:9042:9044"
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=cassandra3
      - CASSANDRA_LISTEN_ADDRESS=cassandra3
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3

networks:
  cassandraNetwork:
    driver: bridge
